<MyInterface>

    calc_field: calc_field

    orientation: 'vertical'

    TextInput:
        id: calc_field
        height: 200
        size_hint: (1, None)
        readonly: True
        disabled: True
        font_size: 64
    
    GridLayout:
        rows: 5
        columns: 4
        padding: 5
        spacing: 5
       
        Button:
            text: "7"
            font_size: 26
            on_press: root.calc_value('7')
        Button:
            text: "8"
            font_size: 26
            on_press: root.calc_value('8')
        Button:
            text: "9"
            font_size: 26
            on_press: root.calc_value('9')
        Button:
            text: "x"
            font_size: 26
            on_press: root.calc_value('*')


        Button:
            text: "4"
            font_size: 26
            on_press: root.calc_value('4')
        Button:
            text: "5"
            font_size: 26
            on_press: root.calc_value('5')
        Button:
            text: "6"
            font_size: 26
            on_press: root.calc_value('6')
        Button:
            text: "-"
            font_size: 26
            on_press: root.calc_value('-')

        Button:
            text: "1"
            font_size: 26
            on_press: root.calc_value('1')
        Button:
            text: "2"
            font_size: 26
            on_press: root.calc_value('2')
        Button:
            text: "3"
            font_size: 26
            on_press: root.calc_value('3')
        Button:
            text: "+"
            font_size: 26
            on_press: root.calc_value('+')    

        Button:
            text: "("
            font_size: 26
            on_press: root.calc_value('(')
        Button:
            text: "0"
            font_size: 26
            on_press: root.calc_value('0')
        Button:
            text: ")"
            font_size: 26
            on_press: root.calc_value(')')
        Button:
            text: "÷"
            font_size: 26
            on_press: root.calc_value('/')


        Button:
            text: "."
            font_size: 26
            on_press: root.calc_value('.')
        Button:
            text: "C"
            font_size: 26
            color: 'red'
            on_press: root.calc_clear()
        Button:
            text: "="
            font_size: 26
            color: 'yellow'
            on_press: root.calc_result()
